server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/andycen?useSSL=false
    username: root
    password: 123456
    tomcat:
      time-between-eviction-runs-millis: 180000
      max-active: 50
      max-idle: 10
      max-wait: 10000
      remove-abandoned: true
      remove-abandoned-timeout: 10
      validation-query: select 1
      num-tests-per-eviction-run: 10
      min-evictable-idle-time-millis: 300000
      log-abandoned: true
  redis:
    host: localhost
    port: 6379

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  typeAliasesPackage: com.andycen.base.core.meta.po

